# Generated by Django 3.2.4 on 2022-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(max_length=300)),
            ],
        ),
    ]
