# Generated by Django 3.2.4 on 2022-01-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn_app', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLibrarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='static')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
